services:
  mysql:
    image: 'mysql:8.2'
    environment:
      - 'MYSQL_DATABASE=hellogsm'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
  redis:
    image: 'redis:7.2'
    ports:
      - '6379'
